export const MODULES = [
  {
    id: 'pg-ctl',
    title: 'pg_ctl Command',
    description: 'Master PostgreSQL server control utility for start, stop, restart, and status operations.',
    icon: '⚙️',
    color: '#64c8ff',
    difficulty: 'Beginner',
    tags: ['pg_ctl', 'server-control', 'cli'],
    path: '/pg-ctl',
    tabs: 6,
  },
  {
    id: 'postgresql-acid-concepts',
    title: 'ACID Concepts',
    description: 'Atomicity, Consistency, Isolation, Durability - the core principles of reliable transactions.',
    icon: '🔒',
    color: '#f87171',
    difficulty: 'Intermediate',
    tags: ['ACID', 'transactions', 'isolation-levels', 'MVCC'], 
    path: '/acid-concepts',
    tabs: 8,
  },
  {
    id: 'pg-ctl-vs-systemd',
    title: 'pg_ctl vs systemd',
    description: 'Compare traditional pg_ctl with modern systemd service management for PostgreSQL.',
    icon: '⚖️',
    color: '#a78bfa',
    difficulty: 'Intermediate',
    tags: ['systemd', 'pg_ctl', 'linux', 'service-management'],
    path: '/pg-ctl-vs-systemd',
    tabs: 7,
  },
  {
    id: 'host-based-auth',
    title: 'Host-Based Authentication',
    description: 'Configure pg_hba.conf for secure client authentication and connection management.',
    icon: '🔐',
    color: '#4ade80',
    difficulty: 'Intermediate',
    tags: ['pg_hba.conf', 'authentication', 'security'],
    path: '/host-based-auth',
    tabs: 7,
  },
  {
    id: 'transaction-log',
    title: 'Transaction Log (WAL)',
    description: 'Deep dive into Write-Ahead Logging, MVCC, checkpoints, and crash recovery.',
    icon: '📝',
    color: '#fbbf24',
    difficulty: 'Advanced',
    tags: ['WAL', 'MVCC', 'transactions', 'crash-recovery', 'pg_waldump'],
    path: '/transaction-log',
    tabs: 9,
  },
  {
    id: 'memory-management',
    title: 'Memory Management & VAS',
    description: 'Understand Virtual Address Space, kernel vs user space, paging, and TLB mechanics.',
    icon: '🧠',
    color: '#f87171',
    difficulty: 'Advanced',
    tags: ['memory', 'VAS', 'kernel', 'paging'],
    path: '/memory-management',
    tabs: 8,
  },
  {
    id: 'tablespaces',
    title: 'PostgreSQL Tablespaces',
    description: 'Physical storage mapping, multi-tier strategies, and performance optimization.',
    icon: '💾',
    color: '#10b981',
    difficulty: 'Intermediate',
    tags: ['tablespaces', 'storage', 'performance'],
    path: '/tablespaces',
    tabs: 8,
  },
  {
    id: 'database-design',
    title: 'Database Design Principles',
    description: 'Normalization, keys & constraints, relationships, indexes, design patterns & anti-patterns.',
    icon: '🗄️',
    color: '#10b981',
    difficulty: 'Intermediate',
    tags: ['normalization', 'schema-design', 'indexes', 'patterns'],
    path: '/database-design',
    tabs: 8,
  },
  {
    id: 'rdbms-types',
    title: 'RDBMS Data Types & Table Types',
    description: 'Numeric, string, datetime, JSONB, UUID, ARRAY, and all PostgreSQL table types: temp, unlogged, partitioned, views.',
    icon: '🗂️',
    color: '#10b981',
    difficulty: 'Intermediate',
    tags: ['data-types', 'table-types', 'JSONB', 'views', 'partitioning'],
    path: '/rdbms-types',
    tabs: 7,
  },
  {
    id: 'state-machine',
    title: 'State Machine Pattern',
    description: 'Model, implement, and query finite state machines in PostgreSQL with transitions, guards, and audit trails.',
    icon: '🔄',
    color: '#a78bfa',
    difficulty: 'Advanced',
    tags: ['FSM', 'workflow', 'transitions', 'audit-trail'],
    path: '/state-machine',
    tabs: 7,
  },
  {
    id: 'data-partitioning',
    title: 'Data Partitioning',
    description: 'RANGE, LIST, and HASH partitioning for massive performance gains and data management.',
    icon: '🗂️',
    color: '#f97316',
    difficulty: 'Advanced',
    tags: ['partitioning', 'RANGE', 'LIST', 'HASH', 'performance'],
    path: '/data-partitioning',
    tabs: 8,
  },
  {
    id: 'scaling',
    title: 'Scaling PostgreSQL',
    description: 'Scale Up/Out, Read Replicas, Streaming & Logical Replication, pgBouncer Connection Pooling, dan Foreign Data Wrapper.',
    icon: '📈',
    color: '#fb923c',
    difficulty: 'Advanced',
    tags: ['scaling', 'replication', 'pgBouncer', 'FDW', 'partitioning', 'read-replica'],
    path: '/scaling',
    tabs: 8,
  },
  {
    id: 'sql-syntax',
    title: 'SQL Syntax PostgreSQL',
    description: 'Referensi lengkap DDL, DML, SELECT, JOIN, Aggregate, CTE, Index, Constraints, Transactions, Functions, JSON, dan Advanced SQL.',
    icon: '📘',
    color: '#64c8ff',
    difficulty: 'Beginner',
    tags: ['SQL', 'DDL', 'DML', 'SELECT', 'JOIN', 'CTE', 'functions', 'JSONB', 'roles', 'GRANT'],
    path: '/sql-syntax',
    tabs: 13,
  },
  {
    id: 'install-postgres',
    title: 'Install PostgreSQL dari Source',
    description: 'Step-by-step kompilasi dan instalasi PostgreSQL 18.3 dari source code ke direktori kustom.',
    icon: '🐘',
    color: '#38bdf8',
    difficulty: 'Beginner',
    tags: ['install', 'source', 'compile', 'configure', 'make'],
    path: '/install-postgres',
    tabs: 10,
  },
  {
    id: 'replication',
    title: 'Replikasi PostgreSQL',
    description: 'Streaming Replication, Logical Replication, Replication Slots, Failover & Promote — panduan lengkap replikasi untuk production.',
    icon: '📡',
    color: '#64c8ff',
    difficulty: 'Advanced',
    tags: ['replication', 'streaming', 'logical', 'standby', 'failover', 'WAL', 'pub-sub', 'HA', 'pg_rewind'],
    path: '/replication',
    tabs: 7,
  },
  {
    id: 'backup-restore',
    title: 'Backup & Restore PostgreSQL',
    description: 'Cold, Warm & Hot Backup — pg_dump, pg_basebackup, WAL Archiving, dan Point-in-Time Recovery (PITR).',
    icon: '💾',
    color: '#4ade80',
    difficulty: 'Intermediate',
    tags: ['backup', 'restore', 'pg_dump', 'pg_basebackup', 'WAL', 'PITR', 'cold', 'warm', 'hot'],
    path: '/backup-restore',
    tabs: 7,
  },
  {
    id: 'benchmarking',
    title: 'Benchmarking PostgreSQL',
    description: 'pgbench, EXPLAIN ANALYZE, pg_stat views — cara mengukur performa, membaca laporan, dan menemukan bottleneck database.',
    icon: '📊',
    color: '#e879f9',
    difficulty: 'Intermediate',
    tags: ['benchmarking', 'pgbench', 'EXPLAIN', 'performance', 'pg_stat_statements', 'TPS', 'latency'],
    path: '/benchmarking',
    tabs: 7,
  },
  {
    id: 'monitoring',
    title: 'Monitoring PostgreSQL',
    description: 'pg_stat_activity, locks, vacuum, bloat, connections, slow query, Prometheus + Grafana, dan alert rules production.',
    icon: '📊',
    color: '#38bdf8',
    difficulty: 'Intermediate',
    tags: ['monitoring', 'pg_stat_activity', 'pg_stat_statements', 'locks', 'vacuum', 'bloat', 'prometheus', 'grafana', 'alerting', 'slow-query'],
    path: '/monitoring',
    tabs: 8,
  },
  {
    id: 'ha-dr',
    title: 'High Availability & Disaster Recovery',
    description: 'Patroni cluster, auto-failover, pg_rewind, Virtual IP, DR standby lintas datacenter, dan production readiness checklist.',
    icon: '🛡️',
    color: '#f87171',
    difficulty: 'Advanced',
    tags: ['HA', 'DR', 'Patroni', 'etcd', 'failover', 'pg_rewind', 'pgBackRest', 'VIP', 'HAProxy', 'RTO', 'RPO'],
    path: '/ha-dr',
    tabs: 7,
  },
]

export const DIFFICULTY_COLORS = {
  Beginner: '#4ade80',
  Intermediate: '#fbbf24',
  Advanced: '#f87171',
}
